src/Entity/Day.php
<?php

namespace App\Entity;

use App\Entity\Traits\AuthorTrait;
use App\Entity\Traits\DateTrait;
use App\Entity\Traits\IdTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DayRepository")
 */
class Day
{
    use IdTrait;
    use DateTrait;
    use AuthorTrait;

    /**
     * @ORM\Column(type="date", unique=true)
     * @Assert\Type("\DateTimeInterface")
     */
    private $date;

    /**
     * @var \DateTime
     * @ORM\Column(type="time_immutable")
     */
    private $startedAt;

    /**
     * @var int
     * @ORM\Column(type="smallint", options={"unsigned":"true"})
     * @Assert\Positive()
     */
    private $bills_50_start;

    /**
     * @var int
     * @ORM\Column(type="smallint", options={"unsigned":"true"})
     * @Assert\Positive()
     */
    private $bills_100_start;

    /**
     * @var int
     * @ORM\Column(type="smallint", nullable=true, options={"unsigned":"true"})
     * @Assert\PositiveOrZero()
     */
    private $bills_50_end;

    /**
     * @var int
     * @ORM\Column(type="smallint", nullable=true, options={"unsigned":"true"})
     * @Assert\PositiveOrZero()
     */
    private $bills_100_end;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $confirmed;

    /**
     * @var UserInterface
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="confirmed_by", referencedColumnName="id")
     */
    protected $confirmedBy;

    /**
     * @var \DateTimeImmutable
     * @ORM\Column(type="time_immutable", nullable=true)
     */
    private $endedAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Assert\Type("numeric")
     * @Assert\PositiveOrZero()
     */
    private $z;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Assert\Type("numeric")
     * @Assert\PositiveOrZero()
     */
    private $debt;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $orderProviders = [];

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $paidProviders = [];

    public function __construct(UserInterface $author)
    {
        $this->date = new \DateTime();
        $this->startedAt = new \DateTimeImmutable();

        $this->author = $author;
        $this->bills_50_start = 1;
        $this->bills_100_start = 1;
        $this->confirmed = false;
    }

    public function isClosed(): bool
    {
        return $this->endedAt !== null;
    }

    public function isToday(): bool
    {
        return $this->date->format('Y-m-d') === (new \DateTime())->format('Y-m-d');
    }

    public function end(\DateTimeImmutable $date = null)
    {
        $this->endedAt = $date ?? new \DateTimeImmutable();
    }

    public function start(\DateTimeImmutable $date = null)
    {
        $this->startedAt = $date ?? new \DateTimeImmutable();
    }

    public function hasEnded(): bool
    {
        return $this->endedAt !== null;
    }

    public function getStartedAt(): \DateTimeImmutable
    {
        return $this->startedAt;
    }

    public function getEndedAt(): ?\DateTimeImmutable
    {
        return $this->endedAt;
    }

    public function getBills50Start(): ?int
    {
        return $this->bills_50_start;
    }

    public function setBills50Start(int $bills_50_start): void
    {
        $this->bills_50_start = $bills_50_start;
    }

    public function getBills100Start(): ?int
    {
        return $this->bills_100_start;
    }

    public function setBills100Start(int $bills_100_start): void
    {
        $this->bills_100_start = $bills_100_start;
    }

    public function getBills50End(): ?int
    {
        return $this->bills_50_end;
    }

    public function setBills50End(int $bills_50_end): void
    {
        $this->bills_50_end = $bills_50_end;
    }

    public function getBills100End(): ?int
    {
        return $this->bills_100_end;
    }

    public function setBills100End(int $bills_100_end): void
    {
        $this->bills_100_end = $bills_100_end;
    }

    public function getZ(): ?float
    {
        return $this->z;
    }

    public function setZ(float $z): self
    {
        $this->z = $z;

        return $this;
    }

    public function getConfirmedBy(): ?UserInterface
    {
        return $this->confirmedBy;
    }

    public function setConfirmedBy(UserInterface $confirmedBy): void
    {
        $this->confirmedBy = $confirmedBy;
    }

    public function confirm(?UserInterface $user)
    {
        $this->confirmed = true;
        $this->confirmedBy = $user;
    }

    public function getOrderProviders(): ?array
    {
        return $this->orderProviders;
    }

    public function setOrderProviders(?array $orderProviders): self
    {
        $this->orderProviders = $orderProviders;

        return $this;
    }

    public function getPaidProviders(): ?array
    {
        return $this->paidProviders;
    }

    public function setPaidProviders(?array $paidProviders): self
    {
        $this->paidProviders = $paidProviders;

        return $this;
    }

    public function isConfirmed(): bool
    {
        return $this->confirmed;
    }

    public function getDebt(): ?float
    {
        return $this->debt;
    }

    public function setDebt(float $debt): self
    {
        $this->debt = $debt;

        return $this;
    }
}

templates/_messages.html.twig
<script src="{{ asset('js/sweetalert.min.js') }}"></script>

{% for type, messages in app.flashes %}
    {% for message in messages %}
        <script>
            Swal.fire({
                    title: '{{ type|trans|capitalize }}',
                    text: '{{ message }}',
                    timer: {{ type == 'error' ? 5000 : 3000 }},
                    icon: '{{ type }}',
                    buttons: false
                });
        </script>
    {% endfor %}
{% endfor %}

templates/balance.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sold zilnic{% endblock %}

{% block header %}
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
{% endblock %}

{% block body %}
    <h1>Sold zilnic</h1>

    <div class="card my-3 p-4">
        <div id="chart"></div>
    </div>

    <div class="card mb-3">
        <table class="table table-striped">
            <thead class="card-header card-header-table">
            <tr>
                <th>Ziua</th>
                <th>Cantitate</th>
            </tr>
            </thead>
            <tbody>
            {% for b in balances|reverse %}
                <tr>
                    <td>{{ include('blocks/_date.html.twig', {'date': b.date}) }}</td>
                    <td style="min-width: 125px;">{{ b.amount|num_for }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% set balances = balances|slice(balances|length - 365) %}

{% block js %}
    <script>
        Highcharts.chart('chart', {
            title: {
                text: ''
            },
            subtitle: {
                text: ''
            },
            yAxis: {
                title: {
                    text: ''
                }
            },
            legend: {
                enabled: false
            },
            plotOptions: {
                series: {
                    pointPlacement: 'on'
                }
            },
            xAxis: {
                categories: [{% for b in balances %}'{{ include('blocks/_date.html.twig', {'date': b.date}) }}'{{ not loop.last ? ', ' }}{% endfor %}],
                labels: {
                    enabled: false
                }
            },

            series: [{
                name: 'Sold',
                data: [{% for b in balances %}{{ b.amount|num_for(0, '') }}{{ not loop.last ? ', ' }}{% endfor %}]
            }],

            credits: {
                enabled: false
            }
        });
    </script>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Magazin{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/selectize.css') }}">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    {% block header %}{% endblock %}
</head>
<body>
{% set route = app.request.attributes.get('_route') %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ path('day') }}">Magazin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ route == 'day' ? 'active' }}">
                <a class="nav-link" href="{{ path('day') }}">Foaia zilei <span class="sr-only">(curent)</span></a>
            </li>

            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item {{ route == 'day_history' ? 'active' }}">
                    <a href="{{ path('day_history') }}" class="nav-link">Istoric</a>
                </li>
            {% endif %}

            <li class="nav-item {{ route == 'monthly_situation' ? 'active' }}">
                <a href="{{ path('monthly_situation') }}" class="nav-link">Situatia lunară</a>
            </li>

            <li class="nav-item dropdown {{ 'category' in route ? 'active' }}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCategoriesLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Furnizori
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownCategoriesLink">
                    <a class="dropdown-item {{ route == 'provider_debt_index' ? 'disabled' }}" href="{{ path('provider_debt_index') }}">Datorii</a>
                    <a class="dropdown-item {{ route == 'provider_index' ? 'disabled' }}" href="{{ path('provider_index') }}">Listă</a>
                </div>
            </li>

            <li class="nav-item dropdown {{ 'category' in route ? 'active' }}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCategoriesLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categorii
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownCategoriesLink">
                    <a class="dropdown-item {{ route == 'expense_category_index' ? 'disabled' }}" href="{{ path('expense_category_index') }}">Ieșiri</a>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a class="dropdown-item {{ route == 'merchandise_category_index' ? 'disabled' }}" href="{{ path('merchandise_category_index') }}">Intrare marfă</a>
                    {% endif %}
                </div>
            </li>

            <li class="nav-item dropdown {{ 'report' in route ? 'active' }}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Rapoarte
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <h6 class="dropdown-header">Pe zile</h6>
                    <a class="dropdown-item {{ route == 'report_sales' ? 'disabled' }}" href="{{ path('report_sales') }}">Vânzări</a>
                    <a class="dropdown-item {{ route == 'report_expenses' ? 'disabled' }}" href="{{ path('report_expenses') }}">Ieșiri</a>
                    <a class="dropdown-item {{ route == 'report_providers' ? 'disabled' }}" href="{{ path('report_providers') }}">Furnizori</a>
                    <a class="dropdown-item {{ route == 'report_merchandise' ? 'disabled' }}" href="{{ path('report_merchandise') }}">Marfă</a>
                    <div class="dropdown-divider"></div>

                    {% if is_granted('ROLE_ADMIN') %}
                        <h6 class="dropdown-header">Pe luni</h6>
                        <a class="dropdown-item {{ route == 'monthly_report' ? 'disabled' }}" href="{{ path('monthly_report') }}">General</a>
                        <a class="dropdown-item {{ route == 'monthly_expenses_report' ? 'disabled' }}" href="{{ path('monthly_expenses_report') }}">Ieșiri</a>
                        <a class="dropdown-item {{ route == 'monthly_merchandise_categories_report' ? 'disabled' }}" href="{{ path('monthly_merchandise_categories_report') }}">Categorii marfă</a>
                        <div class="dropdown-divider"></div>

                        <h6 class="dropdown-header">Pe ani</h6>
                        <a class="dropdown-item {{ route == 'annual_report' ? 'disabled' }}" href="{{ path('annual_report') }}">General</a>
                        <a class="dropdown-item {{ route == 'annual_expenses_report' ? 'disabled' }}" href="{{ path('annual_expenses_report') }}">Categorii marfă</a>
                    {% endif %}
                </div>
            </li>

            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item {{ route == 'balance' ? 'active' }}">
                    <a href="{{ path('balance') }}" class="nav-link">Sold</a>
                </li>
            {% endif %}
        </ul>

        <form method="get" class="form-inline mr-3" action="{{ path('report_merchandise') }}">
            <input class="form-control mr-sm-2" type="search" name="query" placeholder="marfă">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>

        <span class="navbar-text">
            {{ app.user.name }} <a href="{{ path('app_logout') }}" class="btn btn-dark" data-toggle="tooltip" title="Desconectare"><i class="fas fa-sign-out"></i></a>
        </span>
    </div>

    <!-- #TODO mergi la masa, mergi la marfa -->
</nav>

<div class="container pt-3">
    {% block body %}{% endblock %}

    {{ include('_messages.html.twig') }}
</div>

<script src="{{ asset('js/jquery-3.5.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/datepicker.min.js') }}"></script>
<script src="{{ asset('js/selectize.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript">
    jQuery(function ($) {
        $('#js-change-day-datepicker').datepicker(
            'update',
            '{{ currentDate is defined ? currentDate|date('Y-m-d') : 'now'|date('Y-m-d') }}'
        );

        $('.js-selectize').selectize({
            allowEmptyOption: true
        });
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

templates/base_login.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Magazin</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
        .form-signin .checkbox {
            font-weight: 400;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body class="text-center">
<div class="container pt-3">
    {{ include('_messages.html.twig') }}
    {% block body %}{% endblock %}

</div>

<script src="{{ asset('js/jquery-3.5.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script type="text/javascript">
    jQuery(function ($) {
        $('#js-change-day-datepicker').datepicker(
            'update',
            '{{ currentDate is defined ? currentDate|date('Y-m-d') : 'now'|date('Y-m-d') }}'
        );
    });
</script>
{% block js %}{% endblock %}
</body>
</html>

templates/day.html.twig
{% extends 'base.html.twig' %}

{% block title %}Foaia zilei{% endblock %}

{% block body %}
    {{ include('blocks/_day_header.html.twig', { 'date': currentDate, 'totals': transactions['totals'] }) }}

    {% if closeAlert %}
    <div class="alert alert-danger">Nu uita să închizi ziua înainte să pleci!</div>
    {% endif %}

    <div class="row">
        <div class="col-12 col-md-6">
            {{ include('merchandise_payment/list.html.twig', { payments: transactions['payments'] }) }}
        </div>
        <div class="col-12 col-md-6">
            {{ include('expense/list.html.twig', { expenses: transactions['expenses'] }) }}
            {{ include('money/list.html.twig', { money: transactions['money'] }) }}
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-12">
            {{ include('merchandise/list.html.twig', { providers: transactions['providers'] }) }}
        </div>
    </div>

    {% if day and day.isToday and day.hasEnded == false %}
        {% if showReview %}
            {{ form_start(form) }}
            {{ form_errors(form) }}
            <p>Completează câți bani sunt în casă la sfârșitul zilei.</p>

            <div class="row">
                <div class="col-3">
                    {{ form_row(form.bills_50_end) }}
                </div>
                <div class="col-3">
                    {{ form_row(form.bills_100_end) }}
                </div>
                <div class="col-3">
                    {{ form_row(form.z) }}
                </div>
                <div class="col-3">
                    {{ form_row(form.debt) }}
                </div>
            </div>

            {% if form.orderProviders is defined %}
                <div class="row">
                    <div class="col-6">
                        {{ form_row(form.orderProviders) }}
                    </div>
                    <div class="col-6">
                        {{ form_row(form.paidProviders) }}
                    </div>
                </div>
            {% endif %}

            {{ form_end(form) }}
        {% else %}
            <div class="mb-3">
                <a class="btn btn-primary" href="{{ path('day', {'showReview': true}) }}">Închide ziua</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/history.html.twig
{% extends 'base.html.twig' %}

{% block title %}Istoricul zilei{% endblock %}

{% block body %}
    {{ include('blocks/_day_header.html.twig', { 'date': currentDate, 'totals': transactions['totals'] }) }}

    <div class="row">
        <div class="col-12">
            History goes here
        </div>
    </div>
{% endblock %}

templates/log.html.twig
{% extends 'base.html.twig' %}

{% block title %}Istoric{% endblock %}

{% block body %}
    <h1>Istoric tranzactii
        <small>{{ include('blocks/_date.html.twig', {'date': currentDate}) }}</small>
    </h1>

    <div class="row">
        <div class="col-12 col-md-8">
            <form method="get" class="form-inline mb-3">
                {{ include('blocks/_select_providers.html.twig') }}

                <button class="btn btn-outline-primary">
                    Caută <span class="badge badge-light">{{ snapshots|length|default(0) }}</span>
                </button>

            </form>
            {# TODO filtru persoana, filtru actiune, filtru tip #}

            <div class="card mb-3">
                <table class="table">
                    <thead class="card-header card-header-table">
                    <tr>
                        <th>#</th>
                        <th>Persoana</th>
                        <th>Acțiunea</th>
                        <th class="d-none d-md-table-cell">Tip</th>
                        <th class="d-none d-md-table-cell">Ora</th>
                        <th class="d-none d-md-table-cell">Detalii</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for s in snapshots %}
                        <tr style="{{ loop.index % 2 == 0 ? 'background-color: rgba(0,0,0,.05);' }}">
                            <td>{{ loop.index }}</td>
                            <td>
                                {{ s.author.name }}
                                <span class="d-md-none">{{ s.createdAt|date('H:i:s') }}</span>
                            </td>
                            <td>
                                {{ s.type|snapshot_verb }}
                                <span class="badge badge-secondary d-md-none">{{ s.class|snapshot_type }}</span>
                            </td>
                            <td class="d-none d-md-table-cell"><span class="badge badge-secondary">{{ s.class|snapshot_type }}</span></td>
                            <td class="d-none d-md-table-cell">{{ s.createdAt|date('H:i:s') }}</td>
                            <td class="d-none d-md-table-cell">{{ s.content|snapshot_content }}</td>
                        </tr>
                        <tr class="d-md-none" style="{{ loop.index % 2 == 0 ? 'background-color: rgba(0,0,0,.05);' }}">
                            <td colspan="6">{{ s.content|snapshot_content }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">Nici o tranzactie</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-12 col-md-4 order-first order-md-last">
            <ul class="list-group mb-3">
                <li class="list-group-item disabled list-group-flush">Început zi</li>
                <li class="list-group-item"><strong>{{ day.author.name }}</strong> a deschis la <strong>{{ day.startedAt|date('H:s')|default('') }}</strong></li>
                <li class="list-group-item d-flex justify-content-between align-items-center">Bancnote de 50
                    <span class="badge badge-primary badge-pill">{{ day.bills50Start|default(0) }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">Bancnote de 100
                    <span class="badge badge-primary badge-pill">{{ day.bills100Start|default(0) }}</span>
                </li>
            </ul>

            {% if day.endedAt %}
                <ul class="list-group">
                    <li class="list-group-item disabled list-group-flush">Terminare zi</li>
                    <li class="list-group-item">Ziua a fost închisă la <strong>{{ day.endedAt|date('H:s')|default('') }}</strong></li>
                    {% if day.confirmed %}
                        <li class="list-group-item">Confirmată <strong>{{ day.confirmedBy.name }}</strong></li>
                    {% endif %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">Bancnote de 50
                        <span class="badge badge-primary badge-pill">{{ day.bills50End|default(0) }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">Bancnote de 100
                        <span class="badge badge-primary badge-pill">{{ day.bills100End|default(0) }}</span>
                    </li>
                    <li class="list-group-item">Z: {{ day.z|num_for }}</strong></li>
                    <li class="list-group-item">Datorii PayPoint: {{ day.debt|num_for|default(0.00) }}</li>
                </ul>
            {% endif %}


            {% if day.orderProviders %}
                <ul class="list-group mb-4">
                    <li class="list-group-item disabled list-group-flush">Furnizorii la care a dat comandă astăzi</li>
                    {% for p in day.orderProviders %}<li class="list-group-item">{{ p }}</li>{% endfor %}
                </ul>
            {% endif %}

            {% if day.paidProviders %}
                <ul class="list-group mb-4">
                    <li class="list-group-item disabled list-group-flush">Furnizorii care au fost plățiți astăzi</li>
                    {% for p in day.paidProviders %}<li class="list-group-item">{{ p }}</li>{% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/monthly_situation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Situatia lunara{% endblock %}

{% block body %}
    <div class="col-12">
        <h1>Situatia lunară <small>{{ "now"|roDate('MMMM')|upper }}</small></h1>

        <form method="get" class="form-inline">
            <div class="form-group mr-2">
                <select class="form-control" name="month">
                    {% for m, name in months %}
                        <option value="{{ m }}" {{ month == m ? 'selected="selected"' }}>{{ name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group mr-2">
                <select class="form-control" name="year">
                    {% for y in years %}
                        <option value="{{ y }}" {{ y == year ? 'selected="selected"' }}>{{ y }}</option>
                    {% endfor %}
                </select>
            </div>

            <button class="btn btn-outline-primary">Selectează</button>
        </form>

        <div class="card my-3">
            <table class="table table-striped">
                <thead class="card-header card-header-table">
                <tr>
                    <th scope="col">Vanzare zi</th>
                    <th scope="col">Monetar</th>
                    <th scope="col">Iesiri diverse</th>
                    <th scope="col">Marfa facturi</th>
                    <th scope="col">Marfa bonuri</th>
                    <th scope="col">Profit Brut</th>
                </tr>
                </thead>
                <tbody>
                <tr style="background-color: #fff;">
                    <td>{{ sales|num_for }}</td>
                    <td>{{ moneyTotal|num_for }}</td>
                    <td>{{ expenseTotal|num_for }}</td>
                    <td>{{ paymentsTotal[1]|num_for }}</td>
                    <td>{{ paymentsTotal[2]|num_for }}</td>
                    <td>{{ merchandiseTotal|num_for }}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <h4>Ieșiri</h4>

        <div class="card my-3">
            <table class="table table-striped">
                <thead class="card-header card-header-table">
                <tr>
                    {% for c in expensesCategories %}
                        <th scope="col">{{ c.name }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                <tr style="background-color: #fff;">
                    {% for c in expensesCategories %}
                        <td>{{ expensesByCategory[c.id]|num_for }}</td>
                    {% endfor %}
                </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-12 col-md-8">
                <ul class="list-group mb-3">
                    <li class="list-group-item disabled">Socoteli</li>
                    {% set A = expenseTotal + moneyTotal %}
                    <li class="list-group-item"><strong>A:</strong> Total iesiri diverse ({{ expenseTotal|num_for }}) + monetar ({{ moneyTotal|num_for }}) = {{ A|num_for }}</li>

                    {% set B = lastBalance - initialBalance %}
                    <li class="list-group-item"><strong>B:</strong> Total sold final ({{ lastBalance|num_for }}) - total sold initial ({{ initialBalance|num_for }}) = {{ B|num_for }}</li>

                    {% set F = merchandiseTotal - A %}
                    <li class="list-group-item"><strong>Ecuatie finala:</strong> Total profit brut ({{ merchandiseTotal|num_for }}) - A ({{ A|num_for }}) = {{ (merchandiseTotal - A)|num_for }}</li>

                    {% if B != F %}
                        <li class="list-group-item" style="color: #f00;"><strong>Diferenta</strong>: {{ (F - B)|abs|num_for }}</li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-12 col-md-4">
                <ul class="list-group mb-3">
                    <li class="list-group-item disabled">Alte date</li>
                    <li class="list-group-item"><strong>Datorii ramase furnizori</strong>: {{ debtTotal|num_for }}</li>
                    <li class="list-group-item"><strong>Media adaos comercial</strong>: #TODO</li>
                    <li class="list-group-item"><strong>Bonus angajati</strong>: #TODO</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}